# Generated by Django 5.1 on 2024-09-04 23:23

import translate.generate_uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.CharField(editable=False, max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rtl_direction', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(default=translate.generate_uuid.get_a_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('export_strategy', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLanguage',
            fields=[
                ('id', models.CharField(default=translate.generate_uuid.get_a_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('id_project', models.CharField(max_length=36)),
                ('id_language', models.CharField(max_length=25)),
                ('txt_limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Translations',
            fields=[
                ('id', models.CharField(default=translate.generate_uuid.get_a_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('id_project', models.CharField(max_length=36)),
                ('id_language', models.CharField(max_length=25)),
                ('strategy', models.CharField(choices=[('ChatGPT', 'ChatGPT'), ('Google', 'Google'), ('Manual', 'Manual')], max_length=255)),
                ('key', models.CharField(max_length=255, null=True)),
                ('context', models.CharField(blank=True, max_length=1000, null=True)),
                ('value', models.CharField(max_length=1000)),
                ('override_en', models.CharField(blank=True, max_length=1000, null=True)),
                ('flag_export', models.BooleanField(default=False)),
            ],
        ),
    ]
